# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "seeds.rb" do not modify this file, your changes will be clobbered!
# #################################

Country.create!([
     {code: "AF", name: "Afghanistan", nick_name: "Afghanistan", number: 4},
     {code: "AX", name: "Aland Islands", nick_name: "Aland Islands", number: 248},
     {code: "AL", name: "Albania", nick_name: "Albania", number: 8},
     {code: "DZ", name: "Algeria", nick_name: "Algeria", number: 12},
     {code: "AS", name: "American Samoa", nick_name: "American Samoa", number: 16},
     {code: "AD", name: "Andorra", nick_name: "Andorra", number: 20},
     {code: "AO", name: "Angola", nick_name: "Angola", number: 24},
     {code: "AI", name: "Anguilla", nick_name: "Anguilla", number: 660},
     {code: "AQ", name: "Antarctica", nick_name: "Antarctica", number: 10},
     {code: "AG", name: "Antigua and Barbuda", nick_name: "Antigua and Barbuda", number: 28},
     {code: "AR", name: "Argentina", nick_name: "Argentina", number: 32},
     {code: "AM", name: "Armenia", nick_name: "Armenia", number: 51},
     {code: "AW", name: "Aruba", nick_name: "Aruba", number: 533},
     {code: "AU", name: "Australia", nick_name: "Australia", number: 36},
     {code: "AT", name: "Austria", nick_name: "Austria", number: 40},
     {code: "AZ", name: "Azerbaijan", nick_name: "Azerbaijan", number: 31},
     {code: "BS", name: "Bahamas", nick_name: "Bahamas", number: 44},
     {code: "BH", name: "Bahrain", nick_name: "Bahrain", number: 48},
     {code: "BD", name: "Bangladesh", nick_name: "Bangladesh", number: 50},
     {code: "BB", name: "Barbados", nick_name: "Barbados", number: 52},
     {code: "BY", name: "Belarus", nick_name: "Belarus", number: 112},
     {code: "BE", name: "Belgium", nick_name: "Belgium", number: 56},
     {code: "BZ", name: "Belize", nick_name: "Belize", number: 84},
     {code: "BJ", name: "Benin", nick_name: "Benin", number: 204},
     {code: "BM", name: "Bermuda", nick_name: "Bermuda", number: 60},
     {code: "BT", name: "Bhutan", nick_name: "Bhutan", number: 64},
     {code: "VE", name: "Bolivarian Republic of Venezuela", nick_name: "Venezuela", number: 862},
     {code: "BQ", name: "Bonaire, Sint Eustatius and Saba", nick_name: "Bonaire, Sint Eustatius and Saba", number: 535},
     {code: "BA", name: "Bosnia and Herzegovina", nick_name: "Bosnia", number: 70},
     {code: "BW", name: "Botswana", nick_name: "Botswana", number: 72},
     {code: "BV", name: "Bouvet Island", nick_name: "Bouvet Island", number: 74},
     {code: "BR", name: "Brazil", nick_name: "Brazil", number: 76},
     {code: "IO", name: "British Indian Ocean Territory", nick_name: "British Indian Ocean Territory", number: 86},
     {code: "BN", name: "Brunei Darussalam", nick_name: "Brunei", number: 96},
     {code: "BG", name: "Bulgaria", nick_name: "Bulgaria", number: 100},
     {code: "BF", name: "Burkina Faso", nick_name: "Burkina Faso", number: 854},
     {code: "BI", name: "Burundi", nick_name: "Burundi", number: 108},
     {code: "CV", name: "Cabo Verde", nick_name: "Cabo Verde", number: 132},
     {code: "KH", name: "Cambodia", nick_name: "Cambodia", number: 116},
     {code: "CM", name: "Cameroon", nick_name: "Cameroon", number: 120},
     {code: "CA", name: "Canada", nick_name: "Canada", number: 124},
     {code: "KY", name: "Cayman Islands", nick_name: "Cayman Islands", number: 136},
     {code: "CF", name: "Central African Republic", nick_name: "Central African Republic", number: 140},
     {code: "TD", name: "Chad", nick_name: "Chad", number: 148},
     {code: "CL", name: "Chile", nick_name: "Chile", number: 152},
     {code: "CN", name: "China", nick_name: "China", number: 156},
     {code: "CX", name: "Christmas Island", nick_name: "Christmas Island", number: 162},
     {code: "CC", name: "Cocos (Keeling) Islands", nick_name: "Keeling Islands", number: 166},
     {code: "CO", name: "Colombia", nick_name: "Colombia", number: 170},
     {code: "KM", name: "Comoros", nick_name: "Comoros", number: 174},
     {code: "CG", name: "Congo", nick_name: "Congo", number: 178},
     {code: "CK", name: "Cook Islands", nick_name: "Cook Islands", number: 184},
     {code: "CR", name: "Costa Rica", nick_name: "Costa Rica", number: 188},
     {code: "CI", name: "Cote d'Ivoire", nick_name: "Cote d'Ivoire", number: 384},
     {code: "HR", name: "Croatia", nick_name: "Croatia", number: 191},
     {code: "CU", name: "Cuba", nick_name: "Cuba", number: 192},
     {code: "CW", name: "Curacao", nick_name: "Curacao", number: 531},
     {code: "CY", name: "Cyprus", nick_name: "Cyprus", number: 196},
     {code: "CZ", name: "Czechia", nick_name: "Czechia", number: 203},
     {code: "KP", name: "Democratic People's Republic of Korea", nick_name: "North Korea", number: 408},
     {code: "CD", name: "Democratic Republic of the Congo", nick_name: "Congo", number: 180},
     {code: "DK", name: "Denmark", nick_name: "Denmark", number: 208},
     {code: "DJ", name: "Djibouti", nick_name: "Djibouti", number: 262},
     {code: "DM", name: "Dominica", nick_name: "Dominica", number: 212},
     {code: "DO", name: "Dominican Republic", nick_name: "Dominican Republic", number: 214},
     {code: "EC", name: "Ecuador", nick_name: "Ecuador", number: 218},
     {code: "EG", name: "Egypt", nick_name: "Egypt", number: 818},
     {code: "SV", name: "El Salvador", nick_name: "El Salvador", number: 222},
     {code: "GQ", name: "Equatorial Guinea", nick_name: "Equatorial Guinea", number: 226},
     {code: "ER", name: "Eritrea", nick_name: "Eritrea", number: 232},
     {code: "EE", name: "Estonia", nick_name: "Estonia", number: 233},
     {code: "SZ", name: "Eswatini", nick_name: "Eswatini", number: 748},
     {code: "ET", name: "Ethiopia", nick_name: "Ethiopia", number: 231},
     {code: "FK", name: "Falkland Islands (Malvinas)", nick_name: "Falkland Islands", number: 238},
     {code: "FO", name: "Faroe Islands", nick_name: "Faroe Islands", number: 234},
     {code: "FM", name: "Federated States of Micronesia", nick_name: "Micronesia", number: 583},
     {code: "FJ", name: "Fiji", nick_name: "Fiji", number: 242},
     {code: "FI", name: "Finland", nick_name: "Finland", number: 246},
     {code: "FR", name: "France", nick_name: "France", number: 250},
     {code: "GF", name: "French Guiana", nick_name: "French Guiana", number: 254},
     {code: "PF", name: "French Polynesia", nick_name: "French Polynesia", number: 258},
     {code: "TF", name: "French Southern Territories", nick_name: "French Southern Territories", number: 260},
     {code: "GA", name: "Gabon", nick_name: "Gabon", number: 266},
     {code: "GM", name: "Gambia", nick_name: "Gambia", number: 270},
     {code: "GE", name: "Georgia", nick_name: "Georgia", number: 268},
     {code: "DE", name: "Germany", nick_name: "Germany", number: 276},
     {code: "GH", name: "Ghana", nick_name: "Ghana", number: 288},
     {code: "GI", name: "Gibraltar", nick_name: "Gibraltar", number: 292},
     {code: "GR", name: "Greece", nick_name: "Greece", number: 300},
     {code: "GL", name: "Greenland", nick_name: "Greenland", number: 304},
     {code: "GD", name: "Grenada", nick_name: "Grenada", number: 308},
     {code: "GP", name: "Guadeloupe", nick_name: "Guadeloupe", number: 312},
     {code: "GU", name: "Guam", nick_name: "Guam", number: 316},
     {code: "GT", name: "Guatemala", nick_name: "Guatemala", number: 320},
     {code: "GG", name: "Guernsey", nick_name: "Guernsey", number: 831},
     {code: "GN", name: "Guinea", nick_name: "Guinea", number: 324},
     {code: "GW", name: "Guinea-Bissau", nick_name: "Guinea-Bissau", number: 624},
     {code: "GY", name: "Guyana", nick_name: "Guyana", number: 328},
     {code: "HT", name: "Haiti", nick_name: "Haiti", number: 332},
     {code: "HM", name: "Heard Island and McDonald Islands", nick_name: "Heard Island and McDonald Islands", number: 334},
     {code: "VA", name: "Holy See", nick_name: "Holy See", number: 336},
     {code: "HN", name: "Honduras", nick_name: "Honduras", number: 340},
     {code: "HK", name: "Hong Kong", nick_name: "Hong Kong", number: 344},
     {code: "HU", name: "Hungary", nick_name: "Hungary", number: 348},
     {code: "IS", name: "Iceland", nick_name: "Iceland", number: 352},
     {code: "IN", name: "India", nick_name: "India", number: 356},
     {code: "ID", name: "Indonesia", nick_name: "Indonesia", number: 360},
     {code: "IQ", name: "Iraq", nick_name: "Iraq", number: 368},
     {code: "IE", name: "Ireland", nick_name: "Ireland", number: 372},
     {code: "IR", name: "Islamic Republic of Iran", nick_name: "Iran", number: 364},
     {code: "IM", name: "Isle of Man", nick_name: "Isle of Man", number: 833},
     {code: "IL", name: "Israel", nick_name: "Israel", number: 376},
     {code: "IT", name: "Italy", nick_name: "Italy", number: 380},
     {code: "JM", name: "Jamaica", nick_name: "Jamaica", number: 388},
     {code: "JP", name: "Japan", nick_name: "Japan", number: 392},
     {code: "JE", name: "Jersey", nick_name: "Jersey", number: 832},
     {code: "JO", name: "Jordan", nick_name: "Jordan", number: 400},
     {code: "KZ", name: "Kazakhstan", nick_name: "Kazakhstan", number: 398},
     {code: "KE", name: "Kenya", nick_name: "Kenya", number: 404},
     {code: "KI", name: "Kiribati", nick_name: "Kiribati", number: 296},
     {code: "KW", name: "Kuwait", nick_name: "Kuwait", number: 414},
     {code: "KG", name: "Kyrgyzstan", nick_name: "Kyrgyzstan", number: 417},
     {code: "LA", name: "Lao People's Democratic Republic", nick_name: "Laos", number: 418},
     {code: "LV", name: "Latvia", nick_name: "Latvia", number: 428},
     {code: "LB", name: "Lebanon", nick_name: "Lebanon", number: 422},
     {code: "LS", name: "Lesotho", nick_name: "Lesotho", number: 426},
     {code: "LR", name: "Liberia", nick_name: "Liberia", number: 430},
     {code: "LY", name: "Libya", nick_name: "Libya", number: 434},
     {code: "LI", name: "Liechtenstein", nick_name: "Liechtenstein", number: 438},
     {code: "LT", name: "Lithuania", nick_name: "Lithuania", number: 440},
     {code: "LU", name: "Luxembourg", nick_name: "Luxembourg", number: 442},
     {code: "MO", name: "Macao", nick_name: "Macao", number: 446},
     {code: "MG", name: "Madagascar", nick_name: "Madagascar", number: 450},
     {code: "MW", name: "Malawi", nick_name: "Malawi", number: 454},
     {code: "MY", name: "Malaysia", nick_name: "Malaysia", number: 458},
     {code: "MV", name: "Maldives", nick_name: "Maldives", number: 462},
     {code: "ML", name: "Mali", nick_name: "Mali", number: 466},
     {code: "MT", name: "Malta", nick_name: "Malta", number: 470},
     {code: "MH", name: "Marshall Islands", nick_name: "Marshall Islands", number: 584},
     {code: "MQ", name: "Martinique", nick_name: "Martinique", number: 474},
     {code: "MR", name: "Mauritania", nick_name: "Mauritania", number: 478},
     {code: "MU", name: "Mauritius", nick_name: "Mauritius", number: 480},
     {code: "YT", name: "Mayotte", nick_name: "Mayotte", number: 175},
     {code: "MX", name: "Mexico", nick_name: "Mexico", number: 484},
     {code: "MC", name: "Monaco", nick_name: "Monaco", number: 492},
     {code: "MN", name: "Mongolia", nick_name: "Mongolia", number: 496},
     {code: "ME", name: "Montenegro", nick_name: "Montenegro", number: 499},
     {code: "MS", name: "Montserrat", nick_name: "Montserrat", number: 500},
     {code: "MA", name: "Morocco", nick_name: "Morocco", number: 504},
     {code: "MZ", name: "Mozambique", nick_name: "Mozambique", number: 508},
     {code: "MM", name: "Myanmar", nick_name: "Myanmar", number: 104},
     {code: "NA", name: "Namibia", nick_name: "Namibia", number: 516},
     {code: "NR", name: "Nauru", nick_name: "Nauru", number: 520},
     {code: "NP", name: "Nepal", nick_name: "Nepal", number: 524},
     {code: "NL", name: "Netherlands", nick_name: "Netherlands", number: 528},
     {code: "NC", name: "New Caledonia", nick_name: "New Caledonia", number: 540},
     {code: "NZ", name: "New Zealand", nick_name: "New Zealand", number: 554},
     {code: "NI", name: "Nicaragua", nick_name: "Nicaragua", number: 558},
     {code: "NE", name: "Niger", nick_name: "Niger", number: 562},
     {code: "NG", name: "Nigeria", nick_name: "Nigeria", number: 566},
     {code: "NU", name: "Niue", nick_name: "Niue", number: 570},
     {code: "NF", name: "Norfolk Island", nick_name: "Norfolk Island", number: 574},
     {code: "MK", name: "North Macedonia", nick_name: "North Macedonia", number: 807},
     {code: "MP", name: "Northern Mariana Islands", nick_name: "Northern Mariana Islands", number: 580},
     {code: "NO", name: "Norway", nick_name: "Norway", number: 578},
     {code: "OM", name: "Oman", nick_name: "Oman", number: 512},
     {code: "PK", name: "Pakistan", nick_name: "Pakistan", number: 586},
     {code: "PW", name: "Palau", nick_name: "Palau", number: 585},
     {code: "PA", name: "Panama", nick_name: "Panama", number: 591},
     {code: "PG", name: "Papua New Guinea", nick_name: "Papua New Guinea", number: 598},
     {code: "PY", name: "Paraguay", nick_name: "Paraguay", number: 600},
     {code: "PE", name: "Peru", nick_name: "Peru", number: 604},
     {code: "PH", name: "Philippines", nick_name: "Philippines", number: 608},
     {code: "PN", name: "Pitcairn", nick_name: "Pitcairn", number: 612},
     {code: "BO", name: "Plurinational State of Bolivia", nick_name: "Bolivia", number: 68},
     {code: "PL", name: "Poland", nick_name: "Poland", number: 616},
     {code: "PT", name: "Portugal", nick_name: "Portugal", number: 620},
     {code: "PR", name: "Puerto Rico", nick_name: "Puerto Rico", number: 630},
     {code: "QA", name: "Qatar", nick_name: "Qatar", number: 634},
     {code: "KR", name: "Republic of Korea", nick_name: "South Korea", number: 410},
     {code: "MD", name: "Republic of Moldova", nick_name: "Moldova", number: 498},
     {code: "RO", name: "Romania", nick_name: "Romania", number: 642},
     {code: "RU", name: "Russian Federation", nick_name: "Russia", number: 643},
     {code: "RW", name: "Rwanda", nick_name: "Rwanda", number: 646},
     {code: "RE", name: "Réunion", nick_name: "Réunion", number: 638},
     {code: "BL", name: "Saint Barthelemy", nick_name: "Saint Barthelemy", number: 652},
     {code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", nick_name: "Saint Helena, Ascension and Tristan da Cunha", number: 654},
     {code: "KN", name: "Saint Kitts and Nevis", nick_name: "Saint Kitts and Nevis", number: 659},
     {code: "LC", name: "Saint Lucia", nick_name: "Saint Lucia", number: 662},
     {code: "MF", name: "Saint Martin (French part)", nick_name: "Saint Martin", number: 663},
     {code: "PM", name: "Saint Pierre and Miquelon", nick_name: "Saint Pierre and Miquelon", number: 666},
     {code: "VC", name: "Saint Vincent and the Grenadines", nick_name: "Saint Vincent and the Grenadines", number: 670},
     {code: "WS", name: "Samoa", nick_name: "Samoa", number: 882},
     {code: "SM", name: "San Marino", nick_name: "San Marino", number: 674},
     {code: "ST", name: "Sao Tome and Principe", nick_name: "Sao Tome and Principe", number: 678},
     {code: "SA", name: "Saudi Arabia", nick_name: "Saudi Arabia", number: 682},
     {code: "SN", name: "Senegal", nick_name: "Senegal", number: 686},
     {code: "RS", name: "Serbia", nick_name: "Serbia", number: 688},
     {code: "SC", name: "Seychelles", nick_name: "Seychelles", number: 690},
     {code: "SL", name: "Sierra Leone", nick_name: "Sierra Leone", number: 694},
     {code: "SG", name: "Singapore", nick_name: "Singapore", number: 702},
     {code: "SX", name: "Sint Maarten (Dutch part)", nick_name: "Sint Maarten", number: 534},
     {code: "SK", name: "Slovakia", nick_name: "Slovakia", number: 703},
     {code: "SI", name: "Slovenia", nick_name: "Slovenia", number: 705},
     {code: "SB", name: "Solomon Islands", nick_name: "Solomon Islands", number: 90},
     {code: "SO", name: "Somalia", nick_name: "Somalia", number: 706},
     {code: "ZA", name: "South Africa", nick_name: "South Africa", number: 710},
     {code: "GS", name: "South Georgia and the South Sandwich Islands", nick_name: "South Georgia", number: 239},
     {code: "SS", name: "South Sudan", nick_name: "South Sudan", number: 728},
     {code: "ES", name: "Spain", nick_name: "Spain", number: 724},
     {code: "LK", name: "Sri Lanka", nick_name: "Sri Lanka", number: 144},
     {code: "PS", name: "State of Palestine", nick_name: "Palestine", number: 275},
     {code: "SD", name: "Sudan", nick_name: "Sudan", number: 729},
     {code: "SR", name: "Suriname", nick_name: "Suriname", number: 740},
     {code: "SJ", name: "Svalbard and Jan Mayen", nick_name: "Svalbard and Jan Mayen", number: 744},
     {code: "SE", name: "Sweden", nick_name: "Sweden", number: 752},
     {code: "CH", name: "Switzerland", nick_name: "Switzerland", number: 756},
     {code: "SY", name: "Syrian Arab Republic", nick_name: "Syrian Arab Republic", number: 760},
     {code: "TW", name: "Taiwan, Province of China", nick_name: "Taiwan", number: 158},
     {code: "TJ", name: "Tajikistan", nick_name: "Tajikistan", number: 762},
     {code: "TH", name: "Thailand", nick_name: "Thailand", number: 764},
     {code: "TL", name: "Timor-Leste", nick_name: "Timor-Leste", number: 626},
     {code: "TG", name: "Togo", nick_name: "Togo", number: 768},
     {code: "TK", name: "Tokelau", nick_name: "Tokelau", number: 772},
     {code: "TO", name: "Tonga", nick_name: "Tonga", number: 776},
     {code: "TT", name: "Trinidad and Tobago", nick_name: "Trinidad and Tobago", number: 780},
     {code: "TN", name: "Tunisia", nick_name: "Tunisia", number: 788},
     {code: "TR", name: "Turkey", nick_name: "Turkey", number: 792},
     {code: "TM", name: "Turkmenistan", nick_name: "Turkmenistan", number: 795},
     {code: "TC", name: "Turks and Caicos Islands", nick_name: "Turks and Caicos Islands", number: 796},
     {code: "TV", name: "Tuvalu", nick_name: "Tuvalu", number: 798},
     {code: "UG", name: "Uganda", nick_name: "Uganda", number: 800},
     {code: "UA", name: "Ukraine", nick_name: "Ukraine", number: 804},
     {code: "AE", name: "United Arab Emirates", nick_name: "United Arab Emirates", number: 784},
     {code: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nick_name: "United Kingdom", number: 826},
     {code: "TZ", name: "United Republic of Tanzania", nick_name: "Tanzania", number: 834},
     {code: "UM", name: "United States Minor Outlying Islands", nick_name: "United States Minor Outlying Islands", number: 581},
     {code: "US", name: "United States of America", nick_name: "United States", number: 840},
     {code: "UY", name: "Uruguay", nick_name: "Uruguay", number: 858},
     {code: "UZ", name: "Uzbekistan", nick_name: "Uzbekistan", number: 860},
     {code: "VU", name: "Vanuatu", nick_name: "Vanuatu", number: 548},
     {code: "VN", name: "Viet Nam", nick_name: "Viet Nam", number: 704},
     {code: "VG", name: "Virgin Islands (British)", nick_name: "Virgin Islands (British)", number: 92},
     {code: "VI", name: "Virgin Islands (U.S.)", nick_name: "Virgin Islands (U.S.)", number: 850},
     {code: "WF", name: "Wallis and Futuna", nick_name: "Wallis and Futuna", number: 876},
     {code: "EH", name: "Western Sahara", nick_name: "Western Sahara", number: 732},
     {code: "YE", name: "Yemen", nick_name: "Yemen", number: 887},
     {code: "ZM", name: "Zambia", nick_name: "Zambia", number: 894},
     {code: "ZW", name: "Zimbabwe", nick_name: "Zimbabwe", number: 716}
])

PhoneType.create!([
     {name: "Home", description: "Primary home phone number"},
     {name: "Work", description: "Primary work phone number"},
     {name: "Mobile", description: "Personal mobile phone number"},
     {name: "Work Mobile", description: "Company provided mobile phone number"}
])
